// <auto-generated />
using System;
using Infrastructure.Data.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    partial class CarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infrastructure.Data.Models.Car.Car", b =>
                {
                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Added")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Licensed")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearModel")
                        .HasColumnType("int");

                    b.HasKey("WarehouseId", "Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            WarehouseId = 1,
                            Id = 1,
                            Added = new DateTimeOffset(new DateTime(2018, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Volkswagen",
                            Model = "Jetta III",
                            Price = 12947.52m,
                            YearModel = 1995
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 2,
                            Added = new DateTimeOffset(new DateTime(2018, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "Chevrolet",
                            Model = "Corvette",
                            Price = 20019.64m,
                            YearModel = 2004
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 3,
                            Added = new DateTimeOffset(new DateTime(2018, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Expedition EL",
                            Price = 27323.42m,
                            YearModel = 2008
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 4,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "FX",
                            Price = 8541.62m,
                            YearModel = 2010
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 5,
                            Added = new DateTimeOffset(new DateTime(2018, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "GMC",
                            Model = "Safari",
                            Price = 14772.5m,
                            YearModel = 1998
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 6,
                            Added = new DateTimeOffset(new DateTime(2018, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Plymouth",
                            Model = "Colt Vista",
                            Price = 6642.45m,
                            YearModel = 1994
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 7,
                            Added = new DateTimeOffset(new DateTime(2018, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "Escalade ESV",
                            Price = 24925.75m,
                            YearModel = 2008
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 8,
                            Added = new DateTimeOffset(new DateTime(2018, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "Pajero",
                            Price = 28619.45m,
                            YearModel = 2002
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 9,
                            Added = new DateTimeOffset(new DateTime(2017, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Infiniti",
                            Model = "Q",
                            Price = 6103.4m,
                            YearModel = 1995
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 10,
                            Added = new DateTimeOffset(new DateTime(2018, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Mustang",
                            Price = 18992.7m,
                            YearModel = 1993
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 11,
                            Added = new DateTimeOffset(new DateTime(2018, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Chevrolet",
                            Model = "G-Series 1500",
                            Price = 23362.41m,
                            YearModel = 1997
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 12,
                            Added = new DateTimeOffset(new DateTime(2018, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "DeVille",
                            Price = 18371.53m,
                            YearModel = 1993
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 13,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Acura",
                            Model = "NSX",
                            Price = 23175.76m,
                            YearModel = 2001
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 14,
                            Added = new DateTimeOffset(new DateTime(2018, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Ford",
                            Model = "Econoline E250",
                            Price = 26605.54m,
                            YearModel = 1994
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 15,
                            Added = new DateTimeOffset(new DateTime(2017, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "GX",
                            Price = 27395.26m,
                            YearModel = 2005
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 16,
                            Added = new DateTimeOffset(new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Ram Van 3500",
                            Price = 6244.51m,
                            YearModel = 1999
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 17,
                            Added = new DateTimeOffset(new DateTime(2017, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Caravan",
                            Price = 16145.27m,
                            YearModel = 1995
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 18,
                            Added = new DateTimeOffset(new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Dynasty",
                            Price = 15103.84m,
                            YearModel = 1992
                        },
                        new
                        {
                            WarehouseId = 1,
                            Id = 19,
                            Added = new DateTimeOffset(new DateTime(2018, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "Dodge",
                            Model = "Ram 1500",
                            Price = 9977.65m,
                            YearModel = 2004
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 20,
                            Added = new DateTimeOffset(new DateTime(2017, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Maserati",
                            Model = "Coupe",
                            Price = 19957.71m,
                            YearModel = 2005
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 21,
                            Added = new DateTimeOffset(new DateTime(2017, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Isuzu",
                            Model = "Rodeo",
                            Price = 6303.99m,
                            YearModel = 1998
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 22,
                            Added = new DateTimeOffset(new DateTime(2017, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Infiniti",
                            Model = "I",
                            Price = 6910.16m,
                            YearModel = 2002
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 23,
                            Added = new DateTimeOffset(new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Altima",
                            Price = 8252.66m,
                            YearModel = 1994
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 24,
                            Added = new DateTimeOffset(new DateTime(2018, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Toyota",
                            Model = "Corolla",
                            Price = 23732.11m,
                            YearModel = 2009
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 25,
                            Added = new DateTimeOffset(new DateTime(2018, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Acura",
                            Model = "MDX",
                            Price = 8487.19m,
                            YearModel = 2011
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 26,
                            Added = new DateTimeOffset(new DateTime(2017, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "BMW",
                            Model = "7 Series",
                            Price = 29069.52m,
                            YearModel = 1998
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 27,
                            Added = new DateTimeOffset(new DateTime(2018, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Maxima",
                            Price = 11187.68m,
                            YearModel = 2004
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 28,
                            Added = new DateTimeOffset(new DateTime(2017, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Audi",
                            Model = "A8",
                            Price = 16047.9m,
                            YearModel = 1999
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 29,
                            Added = new DateTimeOffset(new DateTime(2018, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Nissan",
                            Model = "Murano",
                            Price = 25859.78m,
                            YearModel = 2005
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 30,
                            Added = new DateTimeOffset(new DateTime(2017, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "Acura",
                            Model = "RL",
                            Price = 13232.13m,
                            YearModel = 2010
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 31,
                            Added = new DateTimeOffset(new DateTime(2018, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "Chariot",
                            Price = 15665.23m,
                            YearModel = 1987
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 32,
                            Added = new DateTimeOffset(new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "GMC",
                            Model = "3500 Club Coupe",
                            Price = 18129.37m,
                            YearModel = 1992
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 33,
                            Added = new DateTimeOffset(new DateTime(2017, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Dakota",
                            Price = 14479.37m,
                            YearModel = 2009
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 34,
                            Added = new DateTimeOffset(new DateTime(2018, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Mercury",
                            Model = "Grand Marquis",
                            Price = 20614.72m,
                            YearModel = 1996
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 35,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Kia",
                            Model = "Sportage",
                            Price = 27106.47m,
                            YearModel = 2001
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 36,
                            Added = new DateTimeOffset(new DateTime(2017, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Chevrolet",
                            Model = "Blazer",
                            Price = 14835.48m,
                            YearModel = 1994
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 37,
                            Added = new DateTimeOffset(new DateTime(2018, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Mercedes-Benz",
                            Model = "SL-Class",
                            Price = 27717.28m,
                            YearModel = 1994
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 38,
                            Added = new DateTimeOffset(new DateTime(2018, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Honda",
                            Model = "Civic Si",
                            Price = 18569.86m,
                            YearModel = 2003
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 39,
                            Added = new DateTimeOffset(new DateTime(2018, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Mercedes-Benz",
                            Model = "CL-Class",
                            Price = 23494.78m,
                            YearModel = 2002
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 40,
                            Added = new DateTimeOffset(new DateTime(2018, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Volkswagen",
                            Model = "Jetta",
                            Price = 25469.49m,
                            YearModel = 2006
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 41,
                            Added = new DateTimeOffset(new DateTime(2018, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "Pontiac",
                            Model = "Grand Prix",
                            Price = 11600.74m,
                            YearModel = 1975
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 42,
                            Added = new DateTimeOffset(new DateTime(2018, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "FX",
                            Price = 22000.62m,
                            YearModel = 2012
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 43,
                            Added = new DateTimeOffset(new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Jaguar",
                            Model = "XK",
                            Price = 10260.79m,
                            YearModel = 2006
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 44,
                            Added = new DateTimeOffset(new DateTime(2018, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Cadillac",
                            Model = "STS",
                            Price = 13740.2m,
                            YearModel = 2007
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 45,
                            Added = new DateTimeOffset(new DateTime(2017, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Pontiac",
                            Model = "Sunfire",
                            Price = 28489.1m,
                            YearModel = 1997
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 46,
                            Added = new DateTimeOffset(new DateTime(2018, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Cadillac",
                            Model = "SRX",
                            Price = 26750.38m,
                            YearModel = 2004
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 47,
                            Added = new DateTimeOffset(new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Land Rover",
                            Model = "Freelander",
                            Price = 21770.59m,
                            YearModel = 2004
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 48,
                            Added = new DateTimeOffset(new DateTime(2018, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Suzuki",
                            Model = "Forenza",
                            Price = 28834.26m,
                            YearModel = 2005
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 49,
                            Added = new DateTimeOffset(new DateTime(2018, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Saab",
                            Model = "9-7X",
                            Price = 25975.68m,
                            YearModel = 2005
                        },
                        new
                        {
                            WarehouseId = 2,
                            Id = 50,
                            Added = new DateTimeOffset(new DateTime(2018, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Ford",
                            Model = "Fusion",
                            Price = 28091.96m,
                            YearModel = 2012
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 51,
                            Added = new DateTimeOffset(new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Cadillac",
                            Model = "Escalade",
                            Price = 7429.18m,
                            YearModel = 2005
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 52,
                            Added = new DateTimeOffset(new DateTime(2017, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Porsche",
                            Model = "Cayenne",
                            Price = 17066.31m,
                            YearModel = 2011
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 53,
                            Added = new DateTimeOffset(new DateTime(2018, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Mercedes-Benz",
                            Model = "SL-Class",
                            Price = 14066.06m,
                            YearModel = 2005
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 54,
                            Added = new DateTimeOffset(new DateTime(2018, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Mitsubishi",
                            Model = "RVR",
                            Price = 22560.18m,
                            YearModel = 1995
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 55,
                            Added = new DateTimeOffset(new DateTime(2017, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "850",
                            Price = 25762.08m,
                            YearModel = 1995
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 56,
                            Added = new DateTimeOffset(new DateTime(2017, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "Honda",
                            Model = "del Sol",
                            Price = 18840.96m,
                            YearModel = 1994
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 57,
                            Added = new DateTimeOffset(new DateTime(2018, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Infiniti",
                            Model = "Q",
                            Price = 28773.14m,
                            YearModel = 1996
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 58,
                            Added = new DateTimeOffset(new DateTime(2018, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Mercedes-Benz",
                            Model = "500E",
                            Price = 17141.08m,
                            YearModel = 1992
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 59,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Envoy XL",
                            Price = 18983.52m,
                            YearModel = 2002
                        },
                        new
                        {
                            WarehouseId = 3,
                            Id = 60,
                            Added = new DateTimeOffset(new DateTime(2018, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "Volkswagen",
                            Model = "Touareg 2",
                            Price = 15611.22m,
                            YearModel = 2008
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 61,
                            Added = new DateTimeOffset(new DateTime(2017, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Saab",
                            Model = "900",
                            Price = 8771m,
                            YearModel = 1987
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 62,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Mazda",
                            Model = "B-Series",
                            Price = 23407.59m,
                            YearModel = 1998
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 63,
                            Added = new DateTimeOffset(new DateTime(2018, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Sierra 3500",
                            Price = 5869.23m,
                            YearModel = 2012
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 64,
                            Added = new DateTimeOffset(new DateTime(2018, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Chevrolet",
                            Model = "Corvette",
                            Price = 16630.67m,
                            YearModel = 1964
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 65,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Toyota",
                            Model = "Tacoma",
                            Price = 11597.18m,
                            YearModel = 1997
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 66,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "GMC",
                            Model = "Sonoma",
                            Price = 18248.21m,
                            YearModel = 2004
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 67,
                            Added = new DateTimeOffset(new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Bugatti",
                            Model = "Veyron",
                            Price = 8051.64m,
                            YearModel = 2009
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 68,
                            Added = new DateTimeOffset(new DateTime(2018, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Dodge",
                            Model = "Ram 1500 Club",
                            Price = 14008.3m,
                            YearModel = 1996
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 69,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Land Rover",
                            Model = "Discovery Series II",
                            Price = 18620.19m,
                            YearModel = 2001
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 70,
                            Added = new DateTimeOffset(new DateTime(2018, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "960",
                            Price = 7316.93m,
                            YearModel = 1993
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 71,
                            Added = new DateTimeOffset(new DateTime(2017, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Chrysler",
                            Model = "LHS",
                            Price = 29444.71m,
                            YearModel = 2001
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 72,
                            Added = new DateTimeOffset(new DateTime(2017, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Porsche",
                            Model = "944",
                            Price = 7396.95m,
                            YearModel = 1984
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 73,
                            Added = new DateTimeOffset(new DateTime(2017, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Subaru",
                            Model = "Legacy",
                            Price = 24491.8m,
                            YearModel = 2010
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 74,
                            Added = new DateTimeOffset(new DateTime(2018, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "Volvo",
                            Model = "XC90",
                            Price = 29009.65m,
                            YearModel = 2003
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 75,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Buick",
                            Model = "Skyhawk",
                            Price = 10567.27m,
                            YearModel = 1985
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 76,
                            Added = new DateTimeOffset(new DateTime(2018, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = true,
                            Make = "GMC",
                            Model = "Envoy XUV",
                            Price = 20997.71m,
                            YearModel = 2004
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 77,
                            Added = new DateTimeOffset(new DateTime(2018, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Volvo",
                            Model = "S60",
                            Price = 28614.95m,
                            YearModel = 2009
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 78,
                            Added = new DateTimeOffset(new DateTime(2018, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Licensed = false,
                            Make = "Pontiac",
                            Model = "Montana",
                            Price = 11221.14m,
                            YearModel = 2000
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 79,
                            Added = new DateTimeOffset(new DateTime(2018, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "RX",
                            Price = 23194.01m,
                            YearModel = 2002
                        },
                        new
                        {
                            WarehouseId = 4,
                            Id = 80,
                            Added = new DateTimeOffset(new DateTime(2018, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Licensed = false,
                            Make = "Lexus",
                            Model = "RX",
                            Price = 17805.45m,
                            YearModel = 2000
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Warehouse.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lat = 47.13111,
                            Location = "West wing",
                            Long = -61.548009999999998,
                            Name = "Warehouse A"
                        },
                        new
                        {
                            Id = 2,
                            Lat = 15.953860000000001,
                            Location = "East wing",
                            Long = 7.0624599999999997,
                            Name = "Warehouse B"
                        },
                        new
                        {
                            Id = 3,
                            Lat = 39.127879999999998,
                            Location = "Suid wing",
                            Long = -2.7139799999999998,
                            Name = "Warehouse C"
                        },
                        new
                        {
                            Id = 4,
                            Lat = -70.843540000000004,
                            Location = "Suid wing",
                            Long = 132.22345000000001,
                            Name = "Warehouse D"
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Car.Car", b =>
                {
                    b.HasOne("Infrastructure.Data.Models.Warehouse.Warehouse", "Warehouse")
                        .WithMany("Cars")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Infrastructure.Data.Models.Warehouse.Warehouse", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
